apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: development
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-redis-master
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: hub.oapol.com/redis:e2e
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      imagePullSecrets:
        - name: registry-secret
