apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  namespace: development
  labels:
    app: redis
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    tier: backend

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-redis-slave
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: hub.oapol.com/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 6379
      imagePullSecrets:
        - name: registry-secret

