apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: hub.oapol.com/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
      imagePullSecrets:
        - name: registry-secret
