apiVersion: v1
kind: Service
metadata:
  name: php-demo-svc
  labels:
    app: php-demo
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: php-demo
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: php-demo-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-demo
    spec:
      containers:
      - name: php-demo
        image: hub.oapol.com/php-tengine:v2
        resources:
        requests:
          cpu: 100m
          memory: 100Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registry-secret
