apiVersion: v1
kind: Service
metadata:
  name: cheyian-zentao-svc
  namespace: production 
  labels:
    app: zentao
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: zentao