apiVersion: v1
kind: Service
metadata:
  name: cheyian-zentao-svc
  namespace: development 
  labels:
    app: zentao
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: zentao

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-zentao
  namespace: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zentao
    spec:
      containers:
      - name: cheyian-zentao
        image: hub.oapol.com/cheyian-zentao:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /www/www/data
            name: data
      volumes:
      - hostPath:
        path: /www/www/data
        name: data
      imagePullSecrets:
        - name: registry-secret
