apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-zentao
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zentao
    spec:
      containers:
        - name: cheyian-zentao
          image: hub.oapol.com/cheyian-zentao:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/www/www/data"
              name: zentao-data
      imagePullSecrets:
        - name: registry-secret
      volumes:
        - hostPath:
          path: "/data/zentao/data"
          name: zentao-data