apiVersion: v1
kind: Service
metadata:
  name: cheyian-auth-svc
  namespace: production
  labels:
    app: cheyian-auth
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: cheyian-auth
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-auth-prod
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cheyian-auth
    spec:
      containers:
      - name: cheyian-auth
        image: hub.oapol.com/cheyian-auth:v58
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: DOCKER_EXPORT_MEMCACHED_HOST
            value: "172.16.0.8"
          - name: DOCKER_EXPORT_MYSQL_DB
            value: "172.16.0.3"
          - name: DOCKER_EXPORT_MYSQL_DB_BASE
            value: "172.16.0.3"
          - name: DOCKER_EXPORT_MYSQL_DB_BASE_PASSWORD
            value: "iHYIFUrz9XpE"
          - name: DOCKER_EXPORT_MYSQL_DB_BASE_USERNAME
            value: "produser"
          - name: DOCKER_EXPORT_MYSQL_DB_PASSWORD
            value: "iHYIFUrz9XpE"
          - name: DOCKER_EXPORT_MYSQL_DB_USERNAME
            value: "produser"
          - name: DOCKER_EXPORT_REDIS_HOST_NAME
            value: "172.16.0.2"
          - name: DOCKER_EXPORT_STATIC_DOMAIN
            value: "http://auth.static.cheyian.com"
          - name: DOCKER_EXPORT_VIN_API_DOMAIN
            value: "http://b2bapi.cheyian.com"
          - name: DOCKER_EXPORT_ANALYSE_DOMAIN
            value: "http://analyse.cheyian.com"
          - name: DOCKER_EXPORT_ISCNAME
            value: '0'
          - name: DOCKER_EXPORT_OSS_ACCESS_ID
            value: "r4g237P433J0Wzet"
          - name: DOCKER_EXPORT_OSS_ACCESS_KEY
            value: "k2HPKcV6dkKX4hfHYS2buYdr8wkfkt"
          - name: DOCKER_EXPORT_OSS_DEFAULT_BUCKET
            value: "cheyian-test"
          - name: DOCKER_EXPORT_OSS_ENDPOINT
            value: "oss-cn-hangzhou.aliyuncs.com"
          - name: DOCKER_EXPORT_UPLOAD_IMAGE_DOMAIN
            value: "http://auth.api.cheyian.com"
          - name: DOCKER_EXPORT_OSS_SYTLE_DOMAIN
            value: "http://cheyian-test.img-cn-hangzhou.aliyuncs.com"
          - name: DOCKER_EXPORT_OSS_CHEYIAN_IMAGE_DOMAIN
            value: "http://cheyian.oss-cn-hangzhou.aliyuncs.com"
          - name: DOCKER_EXPORT_OSS_CHEYIAN_TEST_IMAGE_DOMAIN
            value: "http://%s.oss-cn-hangzhou.aliyuncs.com"
          - name: DOCKER_EXPORT_CREATE_ORDER_DOMAIN
            value: "http://create-order.api.cheyian.com"
      imagePullSecrets:
        - name: registry-secret