apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-b2c-demo
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cheyian-b2c
    spec:
      containers:
      - name: cheyian-b2c
        image: hub.oapol.com/cheyian-b2c:v9
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: YII_ENV
            value: "demo"
      imagePullSecrets:
        - name: registry-secret       