apiVersion: v1
kind: Service
metadata:
  name: php-nginx-svc
  labels:
    app: php-nginx
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    prototcol: TCP
  selector:
    app: php-nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: php-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
      - name: php-nginx
        image: hub.oapol.com/php-nginx:latest
        imagePullPolicy: Always
        command: ['nginx']
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: registry-secret