apiVersion: v1
kind: Service
metadata:
  name: php-fpm-svc
  labels:
    app: php-fpm
spec:
  type: NodePort
  ports:
  - port: 9000
    prototcol: TCP
  selector:
    app: php-fpm
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: php-fpm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: hub.oapol.com/php-nginx:latest
        imagePullPolicy: Always
        command: ['php5-fpm', '--nodaemonize']
        ports:
        - containerPort: 9000
      imagePullSecrets:
        - name: registry-secret
