apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodWIub2Fwb2wuY29tIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlkyaGxlV2xoYmc9PSIsCgkJCSJlbWFpbCI6ICJodWFuZ2hhaXlpbmdAY2hleWlhbi5jb20iCgkJfQoJfQp9"
type: kubernetes.io/dockerconfigjson