apiVersion: v1
kind: Service
metadata:
  name: cheyian-member-svc
  namespace: production
  labels:
    app: cheyian-member
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: cheyian-member
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-member-demo
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cheyian-member
    spec:
      containers:
      - name: cheyian-member
        image: hub.oapol.com/cheyian-member:v15
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
            - name: YII_ENV
              value: "demo"
      imagePullSecrets:
        - name: registry-secret
