apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: production
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 3306
      protocol: TCP
  # label keys and values that must match in order to receive traffic for this service
  selector:
    name: mysql