apiVersion: v1
kind: Service
metadata:
  name: cheyian-qixiubao
  namespace: production
  labels:
    app: qixiubao
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: qixiubao
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-qixiubao-demo
  namespace: production
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qixiubao
    spec:
      containers:
      - name: cheyian-qixiubao
        image: hub.oapol.com/cheyian-qixiubao:v55
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: YII_ENV
            value: "demo"
      imagePullSecrets:
        - name: registry-secret
