cheyian-auth:
    container_name: cheyian-auth
    restart: always
    image: hub.oapol.com/cheyian-auth:v42
    environment:
       - DOCKER_EXPORT_MEMCACHED_HOST=172.16.0.8
       - DOCKER_EXPORT_MYSQL_DB=172.16.0.3
       - DOCKER_EXPORT_MYSQL_DB_BASE=172.16.0.3
       - DOCKER_EXPORT_MYSQL_DB_BASE_PASSWORD=iHYIFUrz9XpE
       - DOCKER_EXPORT_MYSQL_DB_BASE_USERNAME=produser
       - DOCKER_EXPORT_MYSQL_DB_PASSWORD=iHYIFUrz9XpE
       - DOCKER_EXPORT_MYSQL_DB_USERNAME=produser
       - DOCKER_EXPORT_REDIS_HOST_NAME=172.16.0.2
       - DOCKER_EXPORT_REDIS_PASSWORD=E30a84d30
       - DOCKER_EXPORT_STATIC_DOMAIN=http://auth.static.cheyian.com
       - DOCKER_EXPORT_VIN_API_DOMAIN=http://auth.cheyian.com
       - DOCKER_EXPORT_YII_DEBUG=false
       - DOCKER_EXPORT_YII_ENV=prod
    ports:
        - "80:80"