kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    labels:
      app: kube-ui
      version: canary
    name: kube-ui
    namespace: production
  spec:
    replicas: 1
    selector:
      app: kube-ui
      version: canary
    template:
      metadata:
        labels:
          app: kube-ui
          version: canary
      spec:
        containers:
        - name: kube-ui
          image: hub.oapol.com/kubernetes-dashboard-amd64:v1.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            protocol: TCP
          args:
            - --apiserver-host=http://10.0.1.20:8080 
          livenessProbe:
            httpGet:
              path: /
              port: 9090
            initialDelaySeconds: 30
            timeoutSeconds: 30
        imagePullSecrets:
          - name: registry-secret

- kind: Service
  apiVersion: v1
  metadata:
    labels:
      app: kube-ui
    name: kube-ui-svc
    namespace: production
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 9090
    selector:
      app: kube-ui