apiVersion: v1
kind: Service
metadata:
  name: pxc-cluster
  labels:
    unit: pxc-cluster
spec:
  type: NodePort
  ports:
    - port: 3306
      protocol: TCP
      name: mysql
  selector:
    unit: pxc-cluster