apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: grafana
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  namespace: kube-system
  labels:
    app: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: grafana
        app: grafana
    spec:
      containers:
        - name: grafana
          image: hub.oapol.com/grafana-xxl:latest
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        emptyDir:
          medium: Memory
