apiVersion: v1
kind: ReplicationController
metadata:
  name: cheyian-redis
  namespace: development 
spec:
  replicas: 1
  selector:
    name: cheyian-redis
  template:
    metadata:
      labels:
        name: cheyian-redis
    spec:
      containers:
      - name: cheyian-redis
        image: hub.oapol.com/redis:v1
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      imagePullSecrets:
        - name: registry-secret

