apiVersion: v1
kind: Service
metadata:
  labels:
    name: cheyian-sentinel
    role: service
  name: cheyian-redis-sentinel
  namespace: development
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    cheyian-redis-sentinel: "true"
